### ISSUE TITLE
new error in dmr cv option

### ISSUE THREAD

**Issue by myeomans** [TaddyLab/distrom#1]
DMR works fine if I don't use the CV option, but if I turn it on, I get an error every time. I can't imagine what the issue is - the exact same code (with cv=TRUE) was working fine a week ago, but I updated the package since then? anyways... here's the console output that shows the error. 

> dim(X)
> [1] 1639  547
> dim(Y)
> [1] 1639    3
> cl <- makeCluster(detectCores(), type="FORK")
> DM<-dmr(cl=cl, covars=X, counts=Y, cv=F)#, nfold=10)#, select="min")
> summary(DM)
>       Length Class Mode
> SUPG5 11     gamlr list
> SUPG6 11     gamlr list
> SUPG7 11     gamlr list
> DM<-dmr(cl=cl, covars=X, counts=Y, cv=T)#, nfold=10)#, select="min")
> Error in checkForRemoteErrors(val) : 
>   3 nodes produced errors; first error: error in evaluating the argument 'x' in selecting a method for function 't': Error: length(eta) == n is not TRUE

UPDATE: I went back through the github history and the March 16th version works just fine... I'll keep using that until I hear otherwise. Here's the console output:

> source("dmrOLD.R")
> X<-sets[["ALL"]][REAL,]
> Y<-MM[REAL,(colMeans(MM[REAL,])>0)]
> cl <- makeCluster(detectCores(), type="FORK")
> DM<-dmr(cl=cl, covars=X, counts=Y, cv=T, nfold=10, select="min")
> stopCluster(cl)
> summary(DM)
>       Length Class    Mode
> SUPG5 10     cv.gamlr list
> SUPG6 10     cv.gamlr list
> SUPG7 10     cv.gamlr list

**Comment by mataddy** [comment]
thanks mike, that's definitely a bug and I can replicate it.  I'll track it down asap.

**Comment by mataddy** [comment]
thanks for finding this; it was actually a bug in cv.gamlr that I introduced with the last update. I just fixed it, so if you get gamlr from git and install that then you should be fine.  let me know if not and I'll reopen.
