### ISSUE TITLE
Warning: hit max CD iterations

### ISSUE THREAD

**Issue by jestover** [TaddyLab/distrom#13]
I'm not sure if this is an actual issue or just something that should be expected with the gamma lasso regression, but I keep running into the "Warning: hit max CD iterations" on random words.  I've got a sample of 5,000 text documents that I have been using to try and track down the problem.  The vocabulary is 16,350 words and there are 100 coefficients (mostly dummy variables) for the "covars" argument.  I only encounter the issue with 29 of the 16,350 words and the only pattern I can see is that the error always pops up on the second segment of the lambda path (I'm using nlambda = 100).  I'm happy to share the sample data if this seems like an error and replicating it would be helpful. 

Thanks for a great package!  Also, I recently picked up a copy of "Business Data Science" and it is really fantastic!  I wish I had read it as a PhD student.

**Comment by mataddy** [comment]
hey glad you like the book and package.  that warning is usually indicative that the optimization problem is not well posed, usually that you don't have enough info to learn a coefficient for those words and the penalty is not large enough (which would be strange at the second segment... might indicate that some words counts are perfectly predictable from other word counts).  per [gamlr manual](https://cran.r-project.org/web/packages/gamlr/gamlr.pdf) you can also increase the `maxit` argument to see if more iterations allows for convergence.
