### ISSUE TITLE
Outdated and slightly unclear documentation

### ISSUE THREAD

**Issue by vspinu** [TaddyLab/distrom#2]
Hi Matt. Thanks for the great packages and papers. 

A couple of small issues with the docs of `dmr` function.
- "Then each individual is outsourced to Poisson regression ..." could be interpreted as if you are splitting the mattrix by rows (individuals) not by columns. I was quite confused till I digged into the code proper. It might be cleaner to say something like "Then categories are outsourced in uniform chunks to Poisson regression ...".
- `p` in "and p is the dimension of x_i"  is not defined. The sum is ranging over `i` but without the upper limit. 
- the meaning of `bins` arguments is unclear. I digged all the way to `collapse` function  and even then could not figure out what it does till I run it on some examples while stepping through `dmr` function. 
  
  I think it's a very useful argument and the doc could be better by clearly stating what is happening at the lower level and what's the intention of it. Maybe something along "`bins` is the number of quantile cuts for each covariate and is intended for data discretization. The discretized covariates are then interacted to form groups within which the values of original covariates are averaged and counts are summed over.". I think no matter how good the documentation of `bins` is it won't be clear unless a comprehensive example were provided. Note that `collapse` function doesn't contain any examples.
- References to your papers are outdated. For instance "Taddy (2013) The Gamma Lasso" should probably be `Taddy, Matt. 2013. ‘One-Step Estimator Paths for Concave Regularization’. arXiv:1308.5623 [stat], August. http://arxiv.org/abs/1308.5623.`. And the distributed paper: `Taddy, Matt. 2015. ‘Distributed Multinomial Regression’. The Annals of Applied Statistics 9 (3): 1394–1414.`.

**Comment by mataddy** [comment]
thanks @vspinu I'll try to clear these up.

**Comment by mataddy** [comment]
@vspinu these are all great suggestions.  if you are up for it, please create a pull request with the changes made and I'd be very happy to merge it.

**Comment by mataddy** [comment]
went quiet, closing.
