### ISSUE TITLE
Memory error on collapse step

### ISSUE THREAD

**Issue by poorboy44** [TaddyLab/distrom#3]
I'm running DMR on a sparse "v" matrix (1M x 13k columns).  I get an out of memory error during the "collapse" step ( I am specifying bins=2 because "v" is a matrix of 0/1 values).   It looks like the error occurs in this step:

  B <- apply(v,2,cutit) 

I'm not 100% sure, but it could be this statement in the "apply" function is casting the sparse matrix to a dense matrix? Here is the top bit of "apply":

> apply
> function (X, MARGIN, FUN, ...) 
> {
>     FUN <- match.fun(FUN)
>     dl <- length(dim(X))
>     if (!dl) 
>         stop("dim(X) must have a positive length")
>     if (is.object(X)) 
>         X <- if (dl == 2L) 
>             as.matrix(X)
>         else as.array(X)

**Comment by poorboy44** [comment]
This is the specific error message: 
`> test<-collapse(v=bioDTM.1, counts=dtm, mu = NULL, bins = 2)
Error: cannot allocate vector of size 9.8 Gb`

**Comment by mataddy** [comment]
thanks Scotty, I'll look into this.  in the mean time, perhaps you might
want to try and do the binning yourself then fit for a pre-binned matrix.
or alternatively, just go without the binning.

**Comment by mataddy** [comment]
finally had time to read this in detail.  you definitely want to go without the binning in this scenario: even though each element of v is 0/1, the number of unique factor combinations will be enormous for 13k factors.  I've added a warning to this effect.
