### ISSUE TITLE
Issue applying Multinomial Logistic Regression on Congress109 dataset

### ISSUE THREAD

**Issue by MaSt2711** [TaddyLab/distrom#5]
Hi TaddyLab, 
I'm completely new to GitHub, so I'm not sure whether this is the right place to publish my issue. However, after intensive research I decided to go this way: I am currently trying to apply _mnlm_ to the Congress109 dataset and get the following error for an if-loop in the function. 
_`"Error in if (C < p/4) { : argument is of length zero"`_
Do you have any suggestion how to resolve this problem 

Kind regards, 
Max

**Comment by mataddy** [comment]
Hi, can you look at the code in congress109 example and see how yours differs?  I believe that example is working.  Let me know; regardless I should find a way to have a more informative error for whatever is happening here.  Just did an update last week so I might have introduced a bug.

**Comment by MaSt2711** [comment]
Hi, 
thanks for the quick response. I will look into it. 
Now, I also tried the _we8there_-dataset. I used the code as follows below and realized that the columns _we8there$intercept_ & _we8there$loadings_ are empty (_NULL_) if this helps. 
FYI: I am using a Macbook Pro with Intel Core i5 (2.5Ghz) and 8 GB Ram.
Kind regards! 

> library(textir)
> library(gamlr)
> library(parallel)
> data(we8there)      
> dim(we8thereCounts)
> dimnames(we8thereCounts)
> dim(we8thereRatings)
> we8thereRatings[1:3,]
> as.matrix(we8thereCounts)
> as.matrix(we8thereCounts)[12,400]
> g1=min(as.matrix(we8thereCounts)[,]) 
> g2=max(as.matrix(we8thereCounts)[,])
> g1
> g2
> 
> hh=as.matrix(we8thereCounts)[,1000]
> hh
> overall=as.matrix(we8thereRatings[,5])
> nn=2640
> 
> cowords=dim(nn)
> for (i in 1:nn) {
> cowords[i]=sum(as.matrix(we8thereCounts)[,i])
> }
> cowords
> cowords[7]
> 
> nn=6166
> coreview=dim(nn)
> for (i in 1:nn) {
>   coreview[i]=sum(as.matrix(we8thereCounts)[i,])
> }
> 
> plot(sort(coreview,decreasing=TRUE))
> 
> cl=detectCores()
> cl <- makeCluster(detectCores())
> we8mnlm=dmr(cl,we8thereCounts,overall,bins=5)
> 
> we8mnlm
> we8mnlm$intercept`

**Comment by mataddy** [comment]
closing due to lack of report back
