### ISSUE TITLE
Indexing error '[[' in coef.dmr

### ISSUE THREAD

**Issue by nelson-n** [TaddyLab/distrom#8]
Thank you for the awesome package. 

In the `coef` method of the dmr class, counts (columns) that have no observations (all zeroes) and thus `Null` poisson regression coefficients are assigned the coefficient 0. This is done in the following line:

**Line 81** of dmr.R: 
`failures <- sapply(B,is.null)`
`if(any(failures)) B[[which(failures)]] <- Matrix(0)`

Because `[[` can only index a single element and not a vector of elements, this line results in an error if the counts matrix has multiple columns with no observations and thus  multiple features that are `Null`. The temporary solution that I have been using is to replace `[[` with `[` in line 82 which allows for list indexing with a vector of elements. I do not love this solution because it throws the warning message: `implicit list embedding of S4 objects is deprecated`. I am sure that there is an elegant solution, but as it stands `distrom:::coef.dmr` and by extension `textir::srproj` do not work if multiple columns in the matrix have no observation (all zeroes).

**Comment by nelson-n** [comment]
It looks like this issue has been addressed by @groverlynn as a pull request, but it has not been implemented into the package yet.

**Comment by mataddy** [comment]
thanks for this!  did you try @groverlynn solution and does it solve without causing warnings?

**Comment by nelson-n** [comment]
The @groverlynn solution is the fix that I have been using. Functionally it works fine, setting `Null` coefficients to 0 as intended. However, it does throw the warning documented above. I will try to think of why this warning occurs and whether there is a better solution in the coming days!

**Comment by nelson-n** [comment]
Hello @mataddy, the warning message that is thrown by the solution documented above (`implicit list embedding of S4 objects is deprecated`) has its origins all the way back in 2016 with the release of R 3.3.0. The change made in R 3.3.0 is documented as follows: 

_"_`[<-` _with an S4 value into a list currently embeds the S4 object into its own list such that the end results is roughly equivalent to using_ `[[<-` _. That behavior is deprecated. In the **future**, the S4 value will be coerced to a list with_ `as.list()`_."_ 

Clearly we have not reached the **future** where the S4 value is coerced to a list with the `[<-` operator as this would cause an error that currently does not occur when `[<-` is used (note that using `[<-` is the solution that both @groverlynn and I proposed). However, the threat of this change occurring in the future and breaking the entire `distrom:::coef.dmr` method still exists, and using `[<-` as is stands throws the warning message anyways. 

The only solution I can think of that is future proof and gets rid of the warning message is to assign `Null` coefficients the value 0 in an explicit for loop. This would amount to changing **line 82** of dmr.R:

From:
`if(any(failures)) B[[which(failures)]] <- Matrix(0)`

To:
`for (i in which(failures == TRUE)) B[[i]] <- Matrix(0)`

This will cost some speed as you are not assigning all of the `Null` coefficients the value 0 at once, but rather iteratively. However, it is future proof and doesn't throw a confusing warning message at the user. There might be a better solution, but this is the best that I can think of. I hope this explanation clarifies why the warning message is being thrown.

**Comment by mataddy** [comment]
Thanks @lucius-verus-fan.  I agree the for-loop is clunky but I also don't see a better way.  If you put this solution as PR I will accept it.  Thanks again for the help.

**Comment by nelson-n** [comment]
@mataddy the pull request has been submitted. Thank you for working through the issue with me, and thank you for the fantastic package.
